// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ruslanonly/blindtyping/src/internal/models"
	statistics_repository "github.com/ruslanonly/blindtyping/src/internal/repositories/statistics_repository"
	gomock "go.uber.org/mock/gomock"
)

// MockleaderboardRepository is a mock of leaderboardRepository interface.
type MockleaderboardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockleaderboardRepositoryMockRecorder
	isgomock struct{}
}

// MockleaderboardRepositoryMockRecorder is the mock recorder for MockleaderboardRepository.
type MockleaderboardRepositoryMockRecorder struct {
	mock *MockleaderboardRepository
}

// NewMockleaderboardRepository creates a new mock instance.
func NewMockleaderboardRepository(ctrl *gomock.Controller) *MockleaderboardRepository {
	mock := &MockleaderboardRepository{ctrl: ctrl}
	mock.recorder = &MockleaderboardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockleaderboardRepository) EXPECT() *MockleaderboardRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockleaderboardRepository) Count(ctx context.Context, id models.LeaderboardID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockleaderboardRepositoryMockRecorder) Count(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockleaderboardRepository)(nil).Count), ctx, id)
}

// GetPage mocks base method.
func (m *MockleaderboardRepository) GetPage(ctx context.Context, id models.LeaderboardID, start, stop int64) ([]models.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", ctx, id, start, stop)
	ret0, _ := ret[0].([]models.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPage indicates an expected call of GetPage.
func (mr *MockleaderboardRepositoryMockRecorder) GetPage(ctx, id, start, stop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockleaderboardRepository)(nil).GetPage), ctx, id, start, stop)
}

// GetRank mocks base method.
func (m *MockleaderboardRepository) GetRank(ctx context.Context, id models.LeaderboardID, userID models.ID) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRank", ctx, id, userID)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRank indicates an expected call of GetRank.
func (mr *MockleaderboardRepositoryMockRecorder) GetRank(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRank", reflect.TypeOf((*MockleaderboardRepository)(nil).GetRank), ctx, id, userID)
}

// UpsertScore mocks base method.
func (m *MockleaderboardRepository) UpsertScore(ctx context.Context, id models.LeaderboardID, userID models.ID, score models.Score) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertScore", ctx, id, userID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertScore indicates an expected call of UpsertScore.
func (mr *MockleaderboardRepositoryMockRecorder) UpsertScore(ctx, id, userID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertScore", reflect.TypeOf((*MockleaderboardRepository)(nil).UpsertScore), ctx, id, userID, score)
}

// UpsertScores mocks base method.
func (m *MockleaderboardRepository) UpsertScores(ctx context.Context, records []models.ScoreRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertScores", ctx, records)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertScores indicates an expected call of UpsertScores.
func (mr *MockleaderboardRepositoryMockRecorder) UpsertScores(ctx, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertScores", reflect.TypeOf((*MockleaderboardRepository)(nil).UpsertScores), ctx, records)
}

// MockstatisticsRepository is a mock of statisticsRepository interface.
type MockstatisticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockstatisticsRepositoryMockRecorder
	isgomock struct{}
}

// MockstatisticsRepositoryMockRecorder is the mock recorder for MockstatisticsRepository.
type MockstatisticsRepositoryMockRecorder struct {
	mock *MockstatisticsRepository
}

// NewMockstatisticsRepository creates a new mock instance.
func NewMockstatisticsRepository(ctrl *gomock.Controller) *MockstatisticsRepository {
	mock := &MockstatisticsRepository{ctrl: ctrl}
	mock.recorder = &MockstatisticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatisticsRepository) EXPECT() *MockstatisticsRepositoryMockRecorder {
	return m.recorder
}

// GetPersonalBestsPaginated mocks base method.
func (m *MockstatisticsRepository) GetPersonalBestsPaginated(ctx context.Context, limit, offset int) ([]statistics_repository.PersonalBestRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonalBestsPaginated", ctx, limit, offset)
	ret0, _ := ret[0].([]statistics_repository.PersonalBestRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonalBestsPaginated indicates an expected call of GetPersonalBestsPaginated.
func (mr *MockstatisticsRepositoryMockRecorder) GetPersonalBestsPaginated(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonalBestsPaginated", reflect.TypeOf((*MockstatisticsRepository)(nil).GetPersonalBestsPaginated), ctx, limit, offset)
}

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// GetUsernamesByIDs mocks base method.
func (m *MockuserRepository) GetUsernamesByIDs(ctx context.Context, ids []models.ID) (map[models.ID]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsernamesByIDs", ctx, ids)
	ret0, _ := ret[0].(map[models.ID]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsernamesByIDs indicates an expected call of GetUsernamesByIDs.
func (mr *MockuserRepositoryMockRecorder) GetUsernamesByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsernamesByIDs", reflect.TypeOf((*MockuserRepository)(nil).GetUsernamesByIDs), ctx, ids)
}
